theme = "base16_default_dark"

[editor]
true-color = true
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
nbsp = "all"

[keys.normal]
"C-r" = ":reload"
"C-S-r" = ":reload-all"
