[tools]
bottom = "latest"
cargo-binstall = "latest"
"cargo:broot" = "latest"
codex = "latest"
fd = "latest"
helix = "latest"
jaq = "latest"
lsd = "latest"
opencode = "latest"
rg = "latest"
rust = "latest"
tokei = "latest"
typst = "latest"
uv = "latest"
zellij = "latest"

[env]
EDITOR = "hx"

[settings]
minimum_release_age = "0"
